url: https://davidyanez.github.io
baseurl: /

# Site settings
title: David Yanez
email: daveyanez2002@gmail.com
description: "Personal Website about my career, my passion for technology and my thoughs"

# Team names, titles and social links
people:
- name: David Yanez
  pic: dy.jpg
  position: Lead Backend Software Developer
  social:
    - title: github
      url: http://github.com/davidyanez
    - title: linkedin
      url: https://www.linkedin.com/in/david-yanez-67328174/
experience:
  - end_date: Current
    start_date: March 2015
    title: Lead Backend Software Developer
    company:
      name: Stradigi
      url: https://www.stradigi.ca/
    location: Montreal, Quebec
    image: stradigi_logo.png
    description: Lead Backend Software Developer. I work in the design and development of different web services, data analytics application and I lead a team of backend software developers.
    languages: Python, Scala
    databases: MySQL, Neo4j, Elasticsearch, Google DataStore, DynamoDB
    libs: Falcon, Apache Spark, Zappa (AWS serverless), Google App Engine, and more
    tools: Git, Pycharm
    cloud: AWS Services, Google Cloud Services
    sysadmin: Linux, Apache, Nginx
  - end_date: March 2015
    start_date: May 2014
    title: Backend Software Developer
    company:
      name: Global Eagle Entertainment
      url: http://www.geemedia.com
    location: Montreal, Quebec
    image: gee_logo.png
    description: Software Development of the Content Management System that is used to manage content and applications for in-flight systems.
    Languages: Python, C#, ASP.NET
    databases: PostgreSQL
    libs: Flask, Django, Flask, Jinja, SQLAlchemy, Telerik
    tools: SVN, Eclipse, Pycharm, Visual Studio
  - end_date: May 2014
    start_date: May 2012
    title: System Software Specialist
    company:
      name: CAE
      url: http://www.cae.com
    location: Montreal, Quebec
    image: cae_logo2.png
    description: Solve hardware and software issues on Full Flight simulators remotely and directly on the simulator.
    Languages: C, C++
    libs: Flask, Telerik
    tools: Starteam, Visual C++
  - end_date: May 2012
    start_date: May 2011
    title: Backend Software Developer
    company:
      name: QMining
      url: http://www.qmining.com
    location: Montreal, Quebec
    image: qmining_logo.png
    description: Develop a scalable and distributed real-time analytics system using machine learning and Google Cloud Services
    Languages: Python
    databases: Google DataStore
    libs: App Engine
    tools: Mercurial
  - end_date: April 2011
    start_date: August 2007
    title: Data Science and Software Developer
    company:
      name: Silex Creations
      url: http://www.silexcreations.com
    location: Montreal, Quebec
    image: silex_logo.png
    description: Research and develop algorithms and applications for audio, music and speech processing.
    Languages: Matlab, C++, Python, PHP
    databases: MySQL
    libs: Matlab DSP
    tools: Mercurial, Matlab IDE
  - end_date: Jul 2007
    start_date: June 2006
    title: Web Developer
    company:
      name: Telus
      url: http://www.telus.com
    location: Montreal, Quebec
    image: telus_logo.png
    description: Develop Web-Application Timesheet to manage employees hours. Develop a data report systems in MS Access
    Languages: Java, JSP, Visual Basic
    databases: MySQL, MS Access
    libs: Java Server Pages
    tools: Dreamweaver, MS Access, MS Excel
  - end_date: December 2004
    start_date: August 2004
    title: Intership Data Science
    company:
      name: Pratt & Whitey Canada
      url: http://www.pwc.ca
    location: Montreal, Quebec
    image: pwc_logo.jpg
    description: Develop data processing algorithms to monitor aircraft's turbine flight data for the P&WCâ€™s trend data monitoring system WebECTM.
    Languages: Java
    tools: Eclipse
education:
  - school: ETS, University of Quebec
    website: https://en.etsmtl.ca/
    degree: Master of Engineering (M.Eng)
    field: Computer Software Engineering
    start_date: 2011
    end_date: 2014
    Grade: 3.69 / 4.3
    logo:  ets_logo.png
  - school: Concordia University
    website: https://www.concordia.ca/
    degree: Bachelor of Engineering (B.Eng)
    field: Electrical and Electronics Engineering
    start_date: 2003
    end_date: 2007
    Grade: 3.6 / 4.3
    logo:  concordia_logo.png







# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/davidyanez
  - title: linkedin
    url: https://www.linkedin.com/in/david-yanez-67328174/

# Postal address (add as many lines as necessary)
address:
  - line: Montreal, Quebec

# Build settings
markdown: kramdown
permalink: pretty
